### ISSUE TITLE
Framework depending on other library (CocoaPods~>Restkit)

### ISSUE THREAD

**Issue by Aranir** [jverkoey/iOS-Framework#46]
I tried to build my framework which depends on the Restkit0.20 framework. Installing it in the my static library directly via cocoapods created many problems.

I tried to use a https://github.com/jverkoey/iOS-Framework/#developing-the-framework-as-a-dependent-project and import the Restkit via cocoapods into the dependent app, but I still get a compile time error that he can't find the 'RestKit/Restkit.h' file.

Is there a way to directly include a third party library inside my own library if the third party uses cocoapods?

If not, is there another way to include the restkit library in my library and how exactly would I need to go about this?

**Comment by jjramos-developer** [comment]
@paulyoung @Aranir let me guys make sure I'm under the same circumstances. 
1) You created a static framework following the steps depicted here: https://github.com/jverkoey/iOS-Framework/#developing-the-framework-as-a-dependent-project

2) The framework that you developed to be used in other apps, contains third-party dependencies that you were managing (in the framework) using Cocoapods.

3) You wanted the sources of those pods to be included in the .framework you produced

I followed the steps depicted here https://github.com/jverkoey/iOS-Framework/#developing-the-framework-as-a-dependent-project including the update of @paulyoung but when my framework built does not contain the sources of the different pods I have in the workspace.

Am I missing something here in order to get the sources of the pods I'm using included in the framework?

**Comment by paulyoung** [comment]
@jjramos-developer I haven't used CocoaPods since Swift was released but I believe it's currently possible to have CocoaPods pull in your framework's dependencies when consumers use it, at least for dynamic frameworks.

This is based on a discussion I had recently about Argo: https://github.com/thoughtbot/Argo/issues/109#issuecomment-93523013

As to how exactly I'm not sure, but I imagine it's down to putting `spec.dependency` entries in your `.podspec` like Argo does: https://github.com/thoughtbot/Argo/blob/9d55345286f44c88a887083e18cef65627934fd6/Argo.podspec#L19-L20
